# 워크플로우 이름 (GitHub Action UI에 표시되는 이름)
name: React Deploy to S3 (OIDC)

# 언제 실행할지 정의
on:
  push:
    # master 브랜치에 push가 발생하면 실행하겠다
    branches: ["master"]

# Github Actions가 AWS OIDC 인증을 위해 필요한 권한 설정
permissions:
  id-token: write # OIDC 토큰 발급 쓰기 권한
  contents: read # 저장소 코드 읽기 권한

# 실행 단위 설정
jobs: 
  deploy:
    # 실행 환경 (GitHub에서 제공하는 러너)
    runs-on: ubuntu-latest
    
    # 실제로 수행할 명령
    steps: 
      # 1. GitHub 저장소 코드 체크아웃 (코드 가져오기)
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.js 환경 세팅
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 의존성 설치
      - name: Install Dependencies
        run: npm install
        
      # 4. 리액트 프로젝트 빌드
      - name: build React
        run: npm run build
        # 결과물(Artifact) 생성 : dist/

      # 5. AWS 인증 (OIDC 방식)
      - name: configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      # 6. 빌드된 결과물을 s3에 배포(업로드)
      #   빌드된 결과(dist 폴더)를 S3 버킷과 동기화  
      #   --delete : dist 폴더에 없는 파일은 제거 (S3에만 있는 파일을 제거)
      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # 7. CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"